# Generated by Django 2.1.3 on 2018-12-02 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time_start', models.CharField(max_length=50)),
                ('time_end', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=50)),
                ('appointment_with', models.CharField(max_length=50)),
                ('update_time', models.DateField(auto_now=True)),
                ('frist_time', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
